gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
     - joint_finger1
     - joint_finger2
  gains:
      joint_finger1: {p: 100, i: 1, d: 10, i_clamp: 1.0}
      joint_finger2: {p: 100, i: 1, d: 10, i_clamp: 1.0}
  constraints:
      goal_time: 3.0

      joint_finger1: {goal: 0.02}
      joint_finger2: {goal: 0.02}

  
  state_publish_rate:  50
  action_monitor_rate: 30
  stop_trajectory_duration: 0