gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - joint_finger1
     - joint_finger2
  gains:
      joint_finger1: {p: 100, i: 0.01, d: 1}
      joint_finger2: {p: 100, i: 0.01, d: 1}
  constraints:
      goal_time: 10.0

  
  state_publish_rate:  50
  action_monitor_rate: 30
  stop_trajectory_duration: 0